### ISSUE TITLE
Docs plz

### ISSUE THREAD

**Issue by DanielOrourke02** [K5tsu/TimeyTim#1]
Some docs on wtf this is/does would be greatly appreciated.

**Comment by K5tsu** [comment]
i'm rewatching the boys season 1 rn but basically it's a timetable program that generates timetables based on necessity or it can be randomly generated (written in typescript :D). I'm making it cus my brain is way too demented to sit down and make a timetable

**Comment by K5tsu** [comment]
and i'll add the docs when i'm finished with error testing then i'll put it in the repo
